# Generated by Django 5.1 on 2024-05-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbo_uas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='change',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='paid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='saledetails',
            table='sale_details',
        ),
    ]
