# Generated by Django 5.0.4 on 2024-06-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbo_uas', '0003_sale_age_and_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='', max_length=64),
        ),
    ]
