# Generated by Django 5.1 on 2024-06-10 02:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbo_uas', '0004_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetails',
            name='product_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
