# Generated by Django 5.0.4 on 2024-05-27 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_iamge_path_product_image_path_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='employee',
        ),
    ]
