# Generated by Django 5.0.4 on 2024-05-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_productcategory_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='SaleDetails',
        ),
    ]
